class Viewport {
    constructor(canvas, zoom = 1, offset = null) {
        this.canvas = canvas;
        this.ctx = canvas.getContext("2d");
        
        this.zoom = zoom;
        // presets to center of canvas
        this.center = new Point(canvas.width / 2, canvas.height / 2);
        // offset applied to follow viewport position.
        this.offset = offset ? offset : scale(this.center, -1);

        this.drag = {
            start: new Point(0, 0),
            end: new Point(0, 0),
            offset: new Point(0, 0),
            active: false
        }

        this.#addEventListeners();
    }

    reset() {
        this.ctx.restore();
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
        this.ctx.save();
        this.ctx.translate(this.center.x, this.center.y);
        this.ctx.scale(1 / this.zoom, 1 / this.zoom);
        const offset = this.getOffset();
        this.ctx.translate(offset.x, offset.y);
    }

    getMouse(evt, subtractDragOffset = false) {
        const p = new Point(
            // adjust the mouse position taking into account the center (by subtracting) and zoom
            (evt.offsetX - this.center.x) * this.zoom - this.offset.x,
            (evt.offsetY - this.center.y) * this.zoom - this.offset.y
        );

        return subtractDragOffset ? subtract(p, this.drag.offset) : p;
    }

    getOffset() { // combines existing offset with offset from dragging
        return add(this.offset, this.drag.offset);
    }

    #addEventListeners() {
        this.canvas.addEventListener("mousewheel", this.#handleMouseWheel.bind(this));
        this.canvas.addEventListener("mousedown", this.#handleMouseDown.bind(this));
        this.canvas.addEventListener("mousemove", this.#handleMouseMove.bind(this));
        this.canvas.addEventListener("mouseup", this.#handleMouseUp .bind(this));
    }

    #handleMouseDown(evt) {
        if (evt.button == 1) {//middle button
            this.drag.start = this.getMouse(evt);
            this.drag.active = true;
        }
    }

    #handleMouseMove(evt) { // creates drag staus when middle button down drag.end follows mouse, drag.offset generated by subtracting drag.start
        if (this.drag.active) {
            this.drag.end = this.getMouse(evt);
            this.drag.offset = subtract(this.drag.end, this.drag.start);
        }
    }

    #handleMouseUp(evt) {// when middle mouse released, calculates the new offset by adding the final drag offset
    // it then resets the drag values to 0
        if (this.drag.active) {
            this.offset = add(this.offset, this.drag.offset);
            this.drag = {
                start: new Point(0, 0),
                end: new Point(0, 0),
                offset: new Point(0, 0),
                active: false
            };
        }
    }

    #handleMouseWheel(evt) {// creates a zoom scale each time mouse wheel triggered up or down. Uses Math.sign method to simply use the negative or positive value of the movment (the direction).
        const dir = Math.sign(evt.deltaY);
        const step = 0.1;
        this.zoom += dir * step;
        this.zoom = Math.max(0.5, Math.min(5, this.zoom));
    }
}